### ISSUE TITLE
Support o2o:listProperty

### ISSUE THREAD

**Issue by hammar** [hammar/owl2oas#7]
See https://github.com/RealEstateCore/rec/blob/develop/docs/O2OListProperty.md and https://github.com/RealEstateCore/rec/issues/70

**Comment by hammar** [comment]
Example data for an API to parse/generate.

```
{
  "@context": {
    "@base": "http://example.com",
    "label": "http://www.w3.org/2000/01/rdf-schema#label",
    "analytics": "https://w3id.org/rec/analytics/",
    "core": "https://w3id.org/rec/core/"
  },
  "@id": "GUID-GOES-HERE",
  "@type": "analytics:DataSeries",
  "label": "This is a data series!",
  "analytics:seriesMembers": {
    "@list": [ 
      {
      "@id": "OBS1",
      "@type": "core:Observation"
      },
      {
      "@id": "OBS2",
      "@type": "core:Observation"
      }
    ]
  },
  "analytics:generatedBy": [
    {
      "@id": "ADDITION_PROCESS",
      "@type": "analytics:AnalysisProcess"
    }
  ]
}
```

**Comment by hammar** [comment]
OAS YAML:
```
    analytics_DataSeries:
      type: object
      required:
      - '@context'
      properties:
        '@id':
          type: string
        '@type':
          type: string
          default: analytics:DataSeries
        label:
          type: string
        analytics:seriesMembers:
          type: object
          required: 
          - '@list'
          properties:
            '@list':
              type: array
              items:
                type: object
                required:
                - '@id'
                properties:
                  '@id':
                    type: string
                  '@type':
                    type: string
                    default: core:Observation
              minItems: 1
```
